version: "3"
services:

  wiremock:
    container_name: wiremock-standalone
    image: rodolpheche/wiremock:latest
    ports:
      - '8888:8080'
    restart: always
    volumes:
      - './wiremock:/home/wiremock'

  grafana:
    image: grafana_hta
    build:
      context: dockerfile/grafana
    container_name: grafana_hta
    ports:
      - "30000:3000"
    restart: always
    networks:
      - monitor
    depends_on:
      - influxdb
      - chronograf

  influxdb:
    container_name: influxdb
    image: influxdb
    ports:
      - "38086:8086"
    volumes:
      - "${INFLUXDB_DATA_DIR}:/var/lib/influxdb"
    networks:
      - monitor

  chronograf:
    container_name: chronograf
    image: chronograf
    ports:
      - "38888:8888"
    command: --influxdb-url=http://influxdb:8086
    networks:
      - monitor
    depends_on:
      - influxdb

networks:
  monitor:
