version: "3"
services:

  wiremock:
    container_name: wiremock-standalone
    image: rodolpheche/wiremock:latest
    ports:
      - '8888:8080'
    restart: always
    networks:
      - monitor
    volumes:
      - './wiremock:/home/wiremock'

  gatling:
    container_name: gatling-runner
    image: gatling_hta
    build:
      context: dockerfile/gatling
    command: [-s, sample.SampleService]
    networks:
      - monitor
    depends_on:
      - grafana
    environment:
      - LOCAL_USER_ID=`id -u $USER`
    volumes:
      - ./gatling/2.3.0/simulations:/opt/app/java/gatling/user-files/simulations
      - ./gatling/2.3.0/results:/opt/app/java/gatling/results

  grafana:
    container_name: grafana_hta
    image: grafana_hta
    build:
      context: dockerfile/grafana
    ports:
      - "30000:3000"
    restart: always
    networks:
      - monitor
    depends_on:
      - influxdb
      - chronograf

  influxdb:
    container_name: influxdb_hta
    image: influxdb_hta
    build:
      context: dockerfile/influxdb
    ports:
      - "38086:8086"
      - "2003:2003"
    networks:
      - monitor
    environment:
      - "INFLUXDB_DB=myperfdb"

  chronograf:
    container_name: chronograf
    image: chronograf
    ports:
      - "38888:8888"
    command: --influxdb-url=http://influxdb:8086
    networks:
      - monitor
    depends_on:
      - influxdb

networks:
  monitor:
