 # list of datasources that should be deleted from the database
delete_datasources:
   - name: "Influxdb"
     org_id: 1

 # list of datasources to insert/update depending
 # whats available in the datbase
datasources:
   # <string, required> name of the datasource. Required
 - name: "Graphite"
   # <string, required> datasource type. Required
   type: "influxdb"
   # <string, required> access mode. direct or proxy. Required
   access: "direct"
   # <int> org id. will default to org_id 1 if not specified
   org_id: 1
   # <string> url
   url: "http://localhost:38086"
   # <string> database password, if used
   password:
   # <string> database user, if used
   user:
   # <string> database name, if used
   database: "graphite"
   # <bool> enable/disable basic auth
   basic_auth: false
   # <string> basic auth username
   basic_auth_user:
   # <string> basic auth password
   basic_auth_password:
   # <bool> enable/disable with credentials headers
   with_credentials:
   # <bool> mark as default datasource. Max one per org
   is_default: true
   # <map> fields that will be converted to json and stored in json_data
   json_data:
      graphiteVersion: "1.1"
      tlsAuth: true
      tlsAuthWithCACert: true
   # <string> json object of data that will be encrypted.
   secure_json_data:
     tlsCACert: "..."
     tlsClientCert: "..."
     tlsClientKey: "..."
   version: 1
   # <bool> allow users to edit datasources from the UI.
   editable: true
